<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect width="64" height="64" rx="8" fill="#2496ED" />
  <text x="32" y="40" font-size="14" text-anchor="middle" fill="#fff" font-family="Arial, Helvetica, sans-serif">Docker</text>
</svg>
